### ISSUE TITLE
Unrelated Haldex

### ISSUE THREAD

**Issue by chrisgotboost** [threepotMR2/BeanBangerMR2#1]

**Comment by threepotMR2** [comment]
What do you need?

**Comment by chrisgotboost** [comment]
I need to test my software for flashing haldex. Since i was not able to hook my miniwingler to restore in case of crash. I have like 3 haldex modules. Would be very appreciated !

Envoyé de mon iPhone

Le 1 sept. 2024 à 07:23, threepotMR2 ***@***.***> a écrit :

﻿

What do you need?

**Comment by threepotMR2** [comment]
What is your software? is it a fork from vw_flash?

**Comment by chrisgotboost** [comment]
No, its a pc software, Its not made of python at all.

Thanks
Chris

Envoyé de mon iPhone

Le 1 sept. 2024 à 08:56, threepotMR2 ***@***.***> a écrit :

﻿

What is your software? is it a fork from vw_flash?

**Comment by threepotMR2** [comment]
Is it just for VAG or do other brands too?
Yes I'll try at, as long as its not going to brick to many units!

**Comment by chrisgotboost** [comment]
For now its a VAG flasher, but would be cool to add volvo as well, let me know what is best way to communicate other than here.

Thanks
Chris

Envoyé de mon iPhone

Le 1 sept. 2024 à 12:00, threepotMR2 ***@***.***> a écrit :

﻿

Is it just for VAG or do other brands too?
Yes I'll try at, as long as its not going to brick to many units!

**Comment by threepotMR2** [comment]
Problem is, even with a miniwiggler, if you screw up the boot loader blocks the unit is bricked.

Have you actually tried it yourself?

**Comment by chrisgotboost** [comment]
Hi !

If you take a full backup you can’t recover ? How do you screw bootloader, i never flashed one yet, i was told if the flash crash or whatever its not recoverable from UDS, need to be miniwingler.

I could be wrong

Tanks
Chris
Envoyé de mon iPhone

Le 2 sept. 2024 à 03:49, threepotMR2 ***@***.***> a écrit :

﻿

Problem is, even with a miniwiggler, if you screw up the boot loader blocks the unit is bricked.

Have you actually tried it yourself?

**Comment by threepotMR2** [comment]
I have bricked about 10 Gen 5 VAG haldex controllers with the miniwiggler !

**Comment by chrisgotboost** [comment]
So can we talk elsewhere than here ? ahaha

Thanks
Chris
Envoyé de mon iPhone

Le 2 sept. 2024 à 12:58, threepotMR2 ***@***.***> a écrit :

﻿

I have bricked about 10 Gen 5 VAG haldex controllers with the miniwiggler !

**Comment by chrisgotboost** [comment]
@threepotMR2 ?

**Comment by threepotMR2** [comment]
I can't be in the middle of you testing your software.
Firstly I don't have Gen 5 controllers to brick.
And I don't have the time to push your project forwards.
I can't help you with this sorry.
